### ISSUE TITLE
  Missing split_dataset. py file

### ISSUE THREAD

**Issue by sunhui-sh** [vani-or/car_pose_estimation#2]
car_azimuth_predictor .  The folder is missing files for split_dataset.py

**Comment by vani-or** [comment]
Hello, the PASCAL3D+ dataset comes with its own split files.
Here's where it's handled in my code https://github.com/vani-or/car_pose_estimation/blob/4944c6d7731eef4268ac0ed623cb6e63f1fcfef8/car_azimuth_predictor/feature_generation.py#L22

**Comment by sunhui-sh** [comment]
Got it. Thanks for the clarification.
