### ISSUE TITLE
Can you provide the dataset as the link you've mentioned is not working

### ISSUE THREAD

**Issue by Chaitanya887** [vani-or/car_pose_estimation#3]
Can u help me to setup that dataset until you release weight (which eagerly waiting for that to try this model out :), as the results seems so good)

I've gone to the link that you've mentioned under dataset but when clicked 1.1 version it's showing like that and nothings happening 
![image](https://github.com/vani-or/car_pose_estimation/assets/99232731/9b17fc00-71bb-4c6d-8d8c-ddf4bae4a5d3)

**Comment by vani-or** [comment]
@Chaitanya887 Hello!
I checked with curl on Linux and it worked fine
```bash
curl "ftp://cs.stanford.edu/cs/cvgl/PASCAL3D+_release1.1.zip" > pascal.zip
```
Anyway, I put a copy of the archive on the [drive](https://drive.google.com/file/d/1r2MMdYMk97NmuASFmckOcnez_g4erVkI/view?usp=drive_link)

**Comment by Chaitanya887** [comment]
Running the thiscommand 
```
poetry install --with dev
```
that you've mentioned is getting me to this error
![image](https://github.com/vani-or/car_pose_estimation/assets/99232731/b4f1c7bb-6569-4b7c-939a-ad92e2214583)
