### ISSUE TITLE
Request : can u also add a demo file where we can input an image or dir with images and it would predict the output

### ISSUE THREAD

**Issue by Chaitanya887** [vani-or/car_pose_estimation#5]
@vani-or 
Was able to reproduce the results via amazing documentation that you've provided until validation :) 
Could you also provide a script that would be useful to predict on any images in a directory not validation as you've mentioned in your paper
Absolutely loved your work 👍 
![image](https://github.com/vani-or/car_pose_estimation/assets/99232731/16713cb4-fc8b-4257-a7b3-fe477076f58c)

**Comment by vani-or** [comment]
Hello @Chaitanya887 , thanks!
I added the inference script [scripts/inference.py](https://github.com/vani-or/car_pose_estimation/blob/main/scripts/inference.py)

Please also check the README.md for a simple example of usage. You can refer to the script's source code to see how to integrate the model into your application.
